@startuml

(*) --> "Parsing data"
note left: input: XLSX
--> "Converting data\nto interm format"
note right: output: JSON
--> "Identifying\nmissing images"
note right: output: JSON with missing images
if "Missing images allowed" then
    --> [true] "Creating blank images\nfor missing ones"
    note right: output: PNGs
    --> "Generating HTML page"
    note right: output: HTML
    --> (*)
else
    --> [false] "Printing error message"
    --> (*)
endif

@enduml